# Dependencies
markdown:         redcarpet
highlighter:      true

# Permalinks
permalink:        pretty

# Setup
title:            simon's bench
tagline:          'A [digital] notebook on craftsmanship'
description:      ''
url:              https://simonsbench.net

author:
  name:           'simon'
  url:            ''

paginate:         5

# Custom vars
version:          2.0.0

plugins: [jekyll-paginate]
